### ISSUE TITLE
Implementation in Texpad

### ISSUE THREAD

**Issue by felixfunkegithub** [moewew/biblatex-ext#2]
Hello,

I am quite new to using latex so I hope this question is not totally weird. I just got a suggestion in a forum to use the ext-authoryear style for redesigning the citationstyle. I was told to easily drag the files in my latex project folder to make it work.

So I did but I still get an error message which says "package not found"

Do you have any idea how I can get the ext-authoryear package to work with Texpad on a Mac? I am not using MacTex.

Felix

**Comment by moewew** [comment]
I wonder whoever gave you that idea ... ;-)

Anyway, there are a few things going on here. You may want to read a general introduction to TeX and LaTeX to understand what this is about.
In order to use LaTeX you normally install a so-called TeX distribution. That distribution installs some binaries (such as pdfLaTeX, LuaLaTeX, ...) as well as further packages and means to use them.
There are three major distributions nowadays (but there were/are more: https://tex.stackexchange.com/q/239199/)

1. MikTeX for Windows, experimental support for Mac OS and Linux
2. TeX live for Win, Linux and Mac
3. MacTeX (based on TeX live) for Mac, naturally

You must have one of these installed to be able to use (La)TeX. It is via your TeX distribution that you install and update packages.

Texpad is only an editor, just like TeXworks, TeXstudio, ... You simply write your `.tex` files there. Most editors have options to call LaTeX and other auxiliary programmes for you. But they can not do that without an underlying TeX distribution. (See for example in ["What if I haven’t yet installed LaTeX?" on Texpad's support pages](https://www.texpad.com/support/osx/typesetting/managing-distributions))

Now MacTeX is based on TeX live and TeX live has the peculiarity that it is "frozen" for a few weeks a year and that you have to do a full re-install each year to continue to get updates. Have a look at https://tex.stackexchange.com/q/107017/35864 for explanations. MikTeX does not work like that and offers continuous updates all year round. `biblatex-ext` was first released after the TeX live freeze, so at the moment `biblatex-ext` is only available in MikTeX and in [TeX live 2018 pretest](https://www.tug.org/texlive/pretest.html) (not for production use).

Since you are on a Mac you are most likely using MacTeX or raw TeX live in both of these cases you will not be able to install `biblatex-ext` automatically at the moment.

If you want to use the package regardless, download the files from GitHub and place the `.bbx`, `.cbx` and `.def` files in the same directory as your main `.tex` file. Do not move them to a subdirectory.

If that does not help, please share more about your folder set-up, where exactly you placed which files, the error messages you receive, etc. etc.

**Comment by felixfunkegithub** [comment]
Thanks so much I got some very smart supporters here ;)

I think this gave me an excellent overview across the whole topic plus solved my problem!

**Comment by moewew** [comment]
Very well. I'll close this ticket then.
