### ISSUE TITLE
customize names (given-family vice verse)

### ISSUE THREAD

**Issue by LukasCBossert** [moewew/biblatex-ext#3]
Thank you for the great style which makes things easier.

I was wondering if you want to add the possibility to change the position of family and given names in the bibliography?

In the documentation I found three different ways how the names are shown but couldn’t figure out whether this is an option of `biblatex-ext`.

**Comment by moewew** [comment]
You can use all the methods that work for the standard styles (`\DeclareNameAlias{sortname}{family-given}` etc.). At the moment there is no plan to add any more options for the name format in the bibliographies in particular, because I think the standard ways are well known and short and simple enough.

What exactly did you have in mind?

Yes, there are two name formats in the examples in the documentation. That's because some examples use `\fullcite` and some use `\printbibliography`. Maybe I should harmonise that to avoid confusion. I'm curious to know where you found three different ways? Can you show me where that is?

**Comment by LukasCBossert** [comment]
ok, I will use the standard codes then. Fine with me.

At first I thought on page 14 that `Sigfridsson, Emma and Ulf Ryde` is different to the others, but it is actually the same style however the second name is `given-family`.

**Comment by moewew** [comment]
Yes, with the standard styles only the first name in a list is reversed to "family, given" order all other names use "given family" order. I have now reworked the documentation to consistently use `\printbibliography` and with it only one name order. Thank you for the suggestion.
