### ISSUE TITLE
FieldFormat for pages still showing `pp.`

### ISSUE THREAD

**Issue by LukasCBossert** [moewew/biblatex-ext#5]
I am puzzled.
I cannot get rid of the `pp.` however I have set the field format accordingly. (At least I think I did)
```
\documentclass{article}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Book{Plutarch2002,
  title       = {La generazione dell’anima nel Timeo, introduzione, testo critico, traduzione e commento},
  publisher   = {DÁuria},
  editor      = {Ferrari, Franco},
  date        = {2002},
  keywords    = {ancient},
  location    = {Neapel},
  options     = {ancient},
  shortauthor = {Plutarch},
  shorthand   = {Plut. Tim.},
}
\end{filecontents}
\usepackage[style=ext-authoryear, bibstyle=ext-authortitle]{biblatex}
\addbibresource{\jobname.bib}
\DeclareFieldFormat{pages}{#1}


\begin{document}
  \footcite[12,23]{Plutarch2002}
  \printbibliography
\end{document}
```

**Comment by LukasCBossert** [comment]
sorry, my fault....


`\DeclareFieldFormat{postnote}{#1}` was I was looking for.

**Comment by moewew** [comment]
Indeed. Don't forget about `multipostnote` (and maybe `volcitepages`, though that might be a gamble), though.

With `biblatex` 3.11 and later you'll want `\mknormrange{#1}` instead of `#1` in the postnote fields, this is not needed for `pages` because Biber does the normalisation there. See https://github.com/plk/biblatex/issues/293

```
\DeclareFieldFormat{postnote}{\mknormrange{#1}}
\DeclareFieldFormat{multipostnote}{\mknormrange{#1}}
```

**Comment by LukasCBossert** [comment]
wow - you are always so much help! Thank you!
