### ISSUE TITLE
Using `orig`-fields e.g. `origdate`

### ISSUE THREAD

**Issue by LukasCBossert** [moewew/biblatex-ext#6]
I was wondering whether it would be a nice feature of your style using the `orig`-fields as an option.
So far it would be quite some hacking using fields like `origdate`, `origlocation` or `origpublisher`.

**Comment by moewew** [comment]
Mhhh, the `orig...` fields have been falling out of favour even with contributed styles lately, a `related` relation is preferable if possible. I'd rather not encourage users to use `orig...` fields.

Plus there is the issue of how this should look and where things should go. Since `biblatex-ext` does not follow a style guide, I'd have to make up things on the spot.

**Comment by LukasCBossert** [comment]
I definitely see that it preferable using the `related` feature but most the time it is an overload of date: Just for having the `origdate` you would need to set up a whole bibentry. 

My approach here is
```
\DeclareFieldFormat{biblabeldate}{#1\iffieldundef{origyear}{}{\addspace\mkbibbrackets{\thefield{origyear}}}}
```
which is probably not nicely coded as well.

**Comment by moewew** [comment]
Mhhh, I think you should modify the `date+extradate` bibmacro. The standard definition in `ext-authoryear` with `mergedate=compact` (the default) is
```latex
\renewbibmacro*{date+extradate}{%
  \iffieldundef{labelyear}
    {}
    {\printtext[\blx@delimcontext labeldate]{%
       \iflabeldateisdate
         {\printdateextra}
         {\printlabeldateextra}}}}
```
Maybe
```latex
\DeclareFieldFormat{origdate}{\mkbibbrackets{#1}}
%\makeatletter
\renewbibmacro*{date+extradate}{%
  \iffieldundef{labelyear}
    {}
    {\printtext[\blx@delimcontext labeldate]{%
       \iflabeldateisdate
         {\printdateextra}
         {\printlabeldateextra}}
     \iffieldequalstr{labeldatesource}{orig}
       {}
       {\printorigdate}}}
%\makeatother
```
works for you. (The `\makeatletter`...`\makeatother` is only needed in the preamble of a document, in `.bbx` files it can and should be dropped.)

**Comment by LukasCBossert** [comment]
Thank you for that.

**Comment by moewew** [comment]
I'll close this for now as "won't fix", since I don't want to propagate `orig...` fields and I'm not even sure about the design here. I'm open to discuss this again if it turns out that many people would want such a feature. 

Just leave a comment here if you are interested, if you can share a bit about your motivations and desiderata that would help.
